version : '3.7'

services:
  db: 
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: guigui
      MYSQL_USER: guigui
      MYSQL_DATABASE: bank_db
    ports:
      - '3305:3306'
    restart: always
